apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: heapster
    name: heapster
    version: v6
    kubernetes.io/cluster-service: "true"
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v6
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v6
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: heapster
#        image: kubernetes/heapster:canary
        image: gcr.io/google_containers/heapster:v1.1.0
        imagePullPolicy: Always
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default
        - --sink=influxdb:http://monitoring-influxdb:8086
