remote_theme: 'cststack/cststack-jekyll-docs'
title: k8comp Docs
url: "https://cststack.github.io/k8comp"

baseurl: "https://cststack.github.io/k8comp"
google_analytics_key: ""
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: ''
description: k8comp documentation
author:
  name: cststack
  email: ''
  twitter: '' # twitter username without the @ symbol
social:
  name: K8comp Docs
  links:


font-awesome:
  assets: true

sass:
  style: compressed

repository_url: "https://github.com/cststack/k8comp"

# -----
# Build

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-font-awesome-sass

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release
